Repository backend20250319/BE09-Final-4team-FE, pull requests merged in 2025-08, with the labels that each got.

#41 Implement remaining pages for the User Settings module
  app/(announcement)/announcements-detail/announcements.json
  app/approvals/components/form-selection-modal.tsx
  app/members/components/AddMemberModal.tsx
  app/members/components/AddOrganizationModal.tsx
  app/members/components/EditModal.tsx
  app/members/components/LeaderSelectionModal.tsx
  app/members/components/MemberList.tsx
  app/members/components/MemberSelectionModal.tsx
  app/members/components/OrganizationSettingsModal.tsx
  app/members/components/ProfileModal.tsx
  app/members/components/SettingsModal.tsx
  app/members/components/TitlesManager.tsx
  app/members/page.tsx
  app/vacation/vacationmodal.jsx
  components/layout/header.tsx
  components/ui/dialog.tsx
Labels: ✨ Feature, 🎨 Html&css

#43 feat: 문서 페이지 구현
  .gitignore
  app/documents/DocumentsTable.js
  app/documents/page.jsx
  app/documents/page.tsx
  app/documents/upload/page.jsx
  package-lock.json
  package.json
Labels: ✨ Feature

#51 Improve UX for dropdown and members modal
  app/members/components/AddMemberModal.tsx
  app/members/components/AddOrganizationModal.tsx
  app/members/components/EditModal.tsx
  app/members/components/LeaderSelectionModal.tsx
  app/members/components/MemberSelectionModal.tsx
  app/members/components/ProfileModal.tsx
  app/members/components/SimpleDropdown.tsx
  app/members/components/TitlesManager.tsx
  app/members/components/date-input.module.css
  app/members/page.tsx
  app/page.tsx
  components/ui/button.tsx
  components/ui/context-menu.tsx
  components/ui/dropdown-menu.tsx
  components/ui/popover.tsx
  components/ui/switch.tsx
Labels: ✨ Feature, 🎨 Html&css, 🐞 BugFix, 🥰 Accessibility

#66 근무 유형 업데이트, 조직도 개선, 프로필 기능 강화 및 모달 내비게이션 개선
  app/members/components/AddMemberModal.tsx
  app/members/components/AddOrganizationModal.tsx
  app/members/components/EditModal.tsx
  app/members/components/LeaderSelectionModal.tsx
  app/members/components/MemberList.tsx
  app/members/components/MemberSelectionModal.tsx
  app/members/components/OrganizationSettingsModal.tsx
  app/members/components/ProfileModal.tsx
  app/members/components/SimpleDropdown.tsx
  app/members/components/TitlesManager.tsx
  app/members/components/members-modal.module.css
  app/members/components/profile/AccountInfoBlock.tsx
  app/members/components/profile/BasicInfoBlock.tsx
  app/members/components/profile/DetailBlock.tsx
  app/members/components/profile/IntroBlock.tsx
  app/members/components/profile/MetricCard.tsx
  app/members/components/profile/OrganizationBlock.tsx
  app/members/components/profile/PolicyBlock.tsx
  app/members/components/profile/ProfileHeader.tsx
  app/members/components/profile/ProfileModal.tsx
  app/members/components/profile/TitlesBlock.tsx
  app/members/components/profile/types.ts
  app/members/page.tsx
  components/ui/dialog.tsx
  components/ui/popover.tsx
  data/members.json
  hooks/use-members-derived-data.ts
  public/organizations.json
Labels: ✨ Feature, 🎨 Html&css, 🐞 BugFix

#73 Feature/71 enhance frontend features
  app/api/members/route.ts
  app/login/page.tsx
  app/members/components/AddOrganizationModal.tsx
  app/members/components/profile/ProfileModal.tsx
  app/members/page.tsx
  data/members.json
  public/logo.png
  public/logo_p.png
Labels: 🐞 BugFix
