Repository backend20250319/BE09-Final-4team-FE, pull requests merged in 2025-09, with the labels that each got.

#87 구성원 API 연동 및 프로필 모달 '편집하기' 버튼 위치 수정
  app/api/auth/login/route.ts
  app/api/members/bulk/route.ts
  app/api/members/route.ts
  app/login/page.tsx
  app/members/components/LeaderSelectionModal.tsx
  app/members/components/MemberList.tsx
  app/members/components/profile/ProfileModal.tsx
  app/members/page.tsx
  app/page.tsx
  components/layout/header.tsx
  components/layout/main-layout.tsx
  components/ui/spinner.tsx
  hooks/use-auth.ts
  hooks/use-members-derived-data.ts
  hooks/useAuth.ts
Labels: 📬 API

#103 Feat/attendance api integration
  app/page.tsx
  app/settings/workpolicies/create/page.tsx
  app/settings/workpolicies/page.tsx
  app/work/components/CoworkerComponent.tsx
  app/work/components/MyWorkComponent.tsx
  types/jsx-namespace.d.ts
Labels: ✨ Feature, 📬 API

#100 구성원 관리 시스템 기능 대폭 개선 및 검색 기능 강화
  app/members/components/AddOrganizationModal.tsx
  app/members/components/MemberList.tsx
  app/members/components/OrganizationSettingsModal.tsx
  app/members/components/profile/OrganizationBlock.tsx
  app/members/components/profile/ProfileModal.tsx
  app/members/page.tsx
  components/layout/header.tsx
  contexts/auth-context.tsx
  hooks/use-members-derived-data.ts
  lib/services/organization/api.ts
  lib/services/user/api.ts
Labels: ✨ Feature

#110 글로벌 챗봇 컴포넌트 추가 및 동료 근무표 연동 기능 구현 + UI/UX 개선 & 스케줄 시스템 통합
  app/aichat/GlobalAIChat.tsx
  app/layout.tsx
  app/page.tsx
  app/settings/workpolicies/create/page.tsx
  app/work/components/CoworkerComponent.tsx
  app/work/components/MyWorkComponent.tsx
  app/work/components/schedule-utils.ts
  app/work/components/schedulecalendar.css
  components/calendar/schedule-calendar.jsx
  lib/services/attendance/api.ts
  lib/services/attendance/types.ts
  lib/utils/datetime.ts
Labels: 🎨 Html&css, 📬 API, 🔨 Refactor

#113 근무 정책 설정에 연차 정책 카드 생성
  app/settings/workpolicies/components/FixedWorkForm.tsx
  app/settings/workpolicies/components/SelectWorkForm.tsx
  app/settings/workpolicies/components/ShiftWorkForm.tsx
  app/settings/workpolicies/components/TimeWorkForm.tsx
  app/settings/workpolicies/create/page.tsx
  app/vacation/page.tsx
  app/vacation/vacationmodal.tsx
  components/ui/badge.tsx
  components/ui/table.tsx
  lib/services/attendance/README.md
  lib/services/attendance/api.ts
  lib/services/attendance/index.ts
  lib/services/attendance/types.ts
Labels: ✨ Feature

#121 구성원 수정시 타이틀 저장 안되는 이슈 해결
  app/members/components/EditModal.tsx
Labels: 🐞 BugFix
